### ISSUE TITLE
Response model

### ISSUE THREAD

**Issue by Nicialy** [Kheayrig/api-example-social-network#22]
![image](https://user-images.githubusercontent.com/43730314/201547795-ee3ed1fd-864c-4638-be47-e7c43603f4b1.png)
Не исправлено, вместо jsonResponse возращать model которая указана в response_model обработчика. И вместо None, возращать пустую модель с кодом 204. И прокинуть коды status_code в router

**Comment by Kheayrig** [comment]
@Nicialy Проверила ещё раз, нигде не возвращался JSONResponse. А можно подробнее про пустую модель, это возвращать: return Response(status_code=status.HTTP_204_NO_CONTENT)? Плюс закинуть в статус в роутер 204, но не указывать response_model, тк будет ругаться, что AssertionError: Status code 204 must not have a response body?

**Comment by Nicialy** [comment]
Значит, ошибся по поводу JSONResponse. Да, не указываться response_model, просто возвращать пустую модель, которая является классом, если на router уже весит status.code, его не надо дублировать, он оттуда возьмётся. 
Я говорю про пустую модель из pydantic:
 class SuccessfulResponse(BaseModel):
 details: str = Field("Выполнено", title="Статус операции")

**Comment by pavivin** [comment]
Стандартный ответ на все роуты
```python
from starlette.status import HTTP_200_OK

from pydantic import BaseModel, Field


class Response(BaseModel):
    """
        Базовый ответ на запрос
    """
    code: int = Field(HTTP_200_OK, description='Код ответа (http-like)')
    message: str | None = Field("OK", description='Описание кода ответа')
    payload: dict | None = Field(description='Тело ответа')
```

```
Чтобы вернуть в роуте
```python
return Response() # вместо return None
```

Если нужен ответ с другими параметрами
```python
return Response(status_code=201)
```
